# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    container:
      image: debian:11

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: armhf architecture
        run: |
         export APT="apt-get install -yq"
         apt-get update
         apt-get -y upgrade
         dpkg --add-architecture armhf
         apt-get update
         $APT wget bzip2 dpkg-dev dpkg-cross cross-gcc-dev
         $APT crossbuild-essential-armhf apt-utils bison flex
         $APT texinfo file ca-certificates gcc-multilib
         $APT libstdc++6:armhf libgcc1:armhf zlib1g:armhf libncurses5:armhf 
         $APT autoconf automake elfutils:armhf libdebuginfod-dev:armhf

      - name:
        run: |
         ./build.sh
